version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./PUCSR_SISv1:/PUCSR_SISv1
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
